server:
  port: 8411
spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    ip-address: true
#zuul:
#  routes:
#    order-client:
#      path: /orders/**
#      service-id: order-client
#      sensitive-headers:
#  ignored-patterns: /**/admin/**
#  ignored-headers: header1,header2
#  sensitive-headers: Cookie,
ribbon:
  eager-load:
    enabled: true
  okhttp:
    enable: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
