server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone: 192.168.99.100/eureka

    register-with-eureka: false
    fetch-registry: false

#---
#spring.profiles=peer1
#server.port=8761
#eureka.instance.hostname=peer1
#eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka
#eureka.client.service-url.defaultZone=http://peer2:8762/eureka
#---
#spring.profiles=peer2
#server.port=8762
#eureka.instance.hostname=peer2
#eureka.client.service-url.defaultZone=http://peer1/eureka
