server:
  port: 9411
spring:
  application:
    name: zipkin
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false

#http://peer1:8761/eureka,http://peer2:8762/eureka
