server:
  port: 8000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fredye/springcloudconfigsample
          username: Fredye
          password: pass
          search-paths: dev,prod
          clone-on-start: true
        encrypt:
          enabled: true
  rabbitmq:
    host: 192.168.99.100
    post: 5672
    username: guest
    password: guest
