server:
  port: 8011
spring:
  application:
    name: order-client
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    perfer-ip-address: true
feign:
  client:
    config:
      order-service:
        logger-level: full
  hystrix:
    enabled: true

logging:
  level:
    com.dongyun.activity.feign.OrderFeign: debug

